name = "tiny-kanban"
pages_build_output_dir = "public"
compatibility_date = "2026-06-12"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "tiny-kanban-db"
database_id = "9f9ccd66-716a-4f56-a591-9495bb3992d0"
